// Writes src/sounds.ts: the default page-turn sounds, embedded as data URIs.
//
// Embedded rather than shipped as loose files so that `grabfold/sounds` works
// in every bundler, and with none, with no asset configuration at all — and
// only for those who import it; the core never does.
//
//   node scripts/sounds/embed.mjs
//
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "../..");
const { takes, boards } = JSON.parse(readFileSync(resolve(root, "sounds/takes.json"), "utf8"));

const entries = (list) =>
  list
    .map(({ file, landsAt }) => {
      const data = readFileSync(resolve(root, "sounds", file)).toString("base64");
      return `  {\n    // ${file}\n    landsAt: ${landsAt},\n    src: "data:audio/mpeg;base64,${data}",\n  },`;
    })
    .join("\n");

const source = `// Generated by scripts/sounds/embed.mjs from sounds/*.mp3. Do not edit by hand:
// change scripts/sounds/generate.py, run it, then run the embed script.

import type { SoundTake } from "./sound.ts";

/**
 * grabfold's default page-turn sounds: three takes of paper being turned,
 * synthesised from scratch for grabfold and released under its MIT licence.
 *
 * Pass them to \`createPageTurnSound\`. Only the forward turn is here; turning
 * back plays the same takes with their stereo mirrored.
 */
export const defaultPageTurnTakes: readonly SoundTake[] = [
${entries(takes)}
];

/**
 * The same for a rigid leaf — a hard cover, or a page of a board book: a
 * lower swing, a knock of the hinge and a dull thock on landing. Pass them as
 * \`boardTakes\`.
 */
export const defaultBoardTurnTakes: readonly SoundTake[] = [
${entries(boards ?? [])}
];
`;

writeFileSync(resolve(root, "src/sounds.ts"), source);
console.log(`src/sounds.ts  ${takes.length} page takes, ${(boards ?? []).length} board takes, ${(source.length / 1024).toFixed(1)} KB`);
